<%@ Page Title="Add Teacher" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AddTeacher.aspx.cs" Inherits="WebformDemo.AddTeacher" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="container mt-4">
        <h2>Add Teacher</h2>

        <!-- Add Teacher Form -->
        <div class="mb-3">
            <asp:TextBox ID="txtTeacherName" runat="server" CssClass="form-control" Placeholder="Teacher Name"></asp:TextBox>
        </div>

        <div class="mb-3">
            <h5>Select Courses</h5>
            <asp:CheckBoxList ID="chkCourses" runat="server" CssClass="form-check"></asp:CheckBoxList>
        </div>

        <div class="mb-3">
            <asp:Button ID="btnAddTeacher" runat="server" Text="Add Teacher" CssClass="btn btn-primary" OnClick="btnAddTeacher_Click" />
        </div>

        <hr />

        <!-- GridView with Edit/Delete -->
        <asp:GridView ID="gvTeachers" runat="server" AutoGenerateColumns="False"
            DataKeyNames="TeacherId"
            CssClass="table table-striped"
            AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True"
            OnRowDataBound="gvTeachers_RowDataBound"
            OnRowUpdating="gvTeachers_RowUpdating"
            OnRowEditing="gvTeachers_RowEditing"
            OnRowCancelingEdit="gvTeachers_RowCancelingEdit"
            OnRowDeleting="gvTeachers_RowDeleting">
            
            <Columns>
                <asp:BoundField DataField="TeacherId" HeaderText="ID" ReadOnly="True" />

                <asp:TemplateField HeaderText="Teacher Name">
                    <ItemTemplate>
                        <%# Eval("TeacherName") %>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtTeacherName" runat="server" Text='<%# Bind("TeacherName") %>' CssClass="form-control"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Courses">
                    <ItemTemplate>
                        <%# Eval("Courses") %>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:CheckBoxList ID="chkEditCourses" runat="server" CssClass="form-check"></asp:CheckBoxList>
                    </EditItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>

        <asp:Label ID="lblMessage" runat="server" CssClass="text-success mt-2"></asp:Label>
    </div>
</asp:Content>
